title: Random Findings
description: Personal journal of technology exploration.
author: Ryan Kraus
github: https://github.com/kraus.house
about: linux enthusiast
# google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ryan-kraus-1617b7121/"
    - icon: fa-github
      link: "https://github.com/rmkraus"

# share:
    # twitter_username: agusmakmun6
    # fb_appid: 1749788565247320

urls:
    - text: Categories
      url: /category/
    - text: About Me
      url: /about/
    #- text: My Projects
      # url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://kraus.house"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
