title: "# man"
description: Personal journal of technology exploration.
author: Ryan Kraus
github: https://github.com/rmkraus/kraus.house
about: linux enthusiast
# google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg
norton_safeweb_verify: "9kdkibnpp6e1gz8h1-io3fb11344emb2a0rc877lzj2dpi0y81o4y65x1rhkri3z28gmaf4y7epjaxbi29o5j3y0x-zw9lp7wvh3xieu2vhq179qnc58iryfs8sjwswo"

enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ryan-kraus-1617b7121/"
    - icon: fa-github
      link: "https://github.com/rmkraus"
    - icon: fa-envelope
      link: "mailto:rmkraus@gmail.com"

# share:
    # twitter_username: agusmakmun6
    # fb_appid: 1749788565247320

urls:
    - text: '# ls'
      url: /category/
    - text: '# finger'
      url: /about/
    #- text: My Projects
      # url: /projects/
    - text: '# tail -f'
      url: /feed.xml

url: "https://kraus.house"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
